In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

________________________________________________________________________________________________________________________________
weatherdata is a dictionary with multiple data[list] on one key.

In [2]:
weatherdata={
    'day':['1/1/2018','2/12018'],
    'mintemp':[9,10],
    'maxtemp':[20,21],
    'windspeed':[5,6],
    'event':['rain','sunny']
}
df = pd.DataFrame(weatherdata)
print(df)

        day  event  maxtemp  mintemp  windspeed
0  1/1/2018   rain       20        9          5
1   2/12018  sunny       21       10          6

________________________________________________________________________________________________________________________________
rows,cols = df.shape assign rows,cols variables df.shape that could be (x,y) so rows=x,cols=y

In [3]:
print(weatherdata)

rows,cols = df.shape

{'windspeed': [5, 6], 'mintemp': [9, 10], 'day': ['1/1/2018', '2/12018'], 'maxtemp': [20, 21], 'event': ['rain', 'sunny']}

In [4]:
print(rows," ",cols)

2   5

________________________________________________________________________________________________________________________________
df.head() gives first five rows
df.head(x) gives first x rows 
df.tail() gives rows from bottom

In [5]:
print(df.head())
print(df.head(4))
print(df.tail())

        day  event  maxtemp  mintemp  windspeed
0  1/1/2018   rain       20        9          5
1   2/12018  sunny       21       10          6
        day  event  maxtemp  mintemp  windspeed
0  1/1/2018   rain       20        9          5
1   2/12018  sunny       21       10          6
        day  event  maxtemp  mintemp  windspeed
0  1/1/2018   rain       20        9          5
1   2/12018  sunny       21       10          6

In [6]:
print(df.columns)
print(df['event'])
print(type(df['event']))

Index(['day', 'event', 'maxtemp', 'mintemp', 'windspeed'], dtype='object')
0     rain
1    sunny
Name: event, dtype: object
<class 'pandas.core.series.Series'>

In [7]:
df = pd.read_csv('nseInfy.csv')
print(df)

    Symbol Series         Date  Prev Close  Open Price  High Price  Low Price  \
0     INFY     EQ  16-Jun-2016     1189.95     1189.50     1189.50    1170.10
1     INFY     EQ  17-Jun-2016     1186.00     1189.00     1192.75    1175.10
2     INFY     EQ  20-Jun-2016     1179.50     1181.00     1211.80    1179.70
3     INFY     EQ  21-Jun-2016     1208.75     1211.20     1214.80    1195.65
4     INFY     EQ  22-Jun-2016     1206.10     1204.00     1211.95    1188.15
5     INFY     EQ  23-Jun-2016     1199.50     1197.30     1214.85    1193.35
6     INFY     EQ  24-Jun-2016     1211.60     1188.00     1199.00    1160.00
7     INFY     EQ  27-Jun-2016     1194.55     1172.05     1183.20    1160.00
8     INFY     EQ  28-Jun-2016     1166.20     1162.80     1172.50    1155.10
9     INFY     EQ  29-Jun-2016     1159.15     1169.00     1179.90    1160.20
10    INFY     EQ  30-Jun-2016     1176.85     1180.50     1184.50    1167.95
11    INFY     EQ  01-Jul-2016     1170.80     1180.00     1180.00    1170.10
12    INFY     EQ  04-Jul-2016     1172.40     1176.20     1194.60    1176.20
13    INFY     EQ  05-Jul-2016     1183.95     1185.00     1187.50    1171.05
14    INFY     EQ  07-Jul-2016     1175.45     1168.70     1171.00    1155.00
15    INFY     EQ  08-Jul-2016     1157.25     1163.00     1167.00    1153.50
16    INFY     EQ  11-Jul-2016     1158.20     1167.40     1178.70    1160.00
17    INFY     EQ  12-Jul-2016     1175.05     1180.00     1180.35    1168.00
18    INFY     EQ  13-Jul-2016     1176.55     1180.00     1195.80    1175.20
19    INFY     EQ  14-Jul-2016     1193.80     1195.00     1196.05    1164.00
20    INFY     EQ  15-Jul-2016     1176.25     1189.50     1189.90    1052.00
21    INFY     EQ  18-Jul-2016     1072.55     1077.25     1084.90    1055.15
22    INFY     EQ  19-Jul-2016     1081.95     1088.60     1090.00    1074.10
23    INFY     EQ  20-Jul-2016     1086.95     1070.00     1089.90    1070.00
24    INFY     EQ  21-Jul-2016     1083.10     1079.00     1087.20    1075.60
25    INFY     EQ  22-Jul-2016     1079.90     1070.00     1079.90    1066.70
26    INFY     EQ  25-Jul-2016     1072.45     1063.00     1083.25    1063.00
27    INFY     EQ  26-Jul-2016     1080.85     1070.35     1089.90    1070.35
28    INFY     EQ  27-Jul-2016     1088.70     1084.70     1096.50    1078.55
29    INFY     EQ  28-Jul-2016     1085.35     1085.40     1086.95    1074.05
..     ...    ...          ...         ...         ...         ...        ...
467   INFY     EQ  07-May-2018     1173.10     1181.25     1190.00    1175.50
468   INFY     EQ  08-May-2018     1183.00     1177.90     1177.90    1161.05
469   INFY     EQ  09-May-2018     1165.55     1167.50     1176.90    1163.00
470   INFY     EQ  10-May-2018     1170.70     1176.00     1183.00    1162.85
471   INFY     EQ  11-May-2018     1168.00     1172.30     1183.20    1166.05
472   INFY     EQ  14-May-2018     1180.75     1184.35     1191.50    1170.00
473   INFY     EQ  15-May-2018     1189.30     1188.10     1208.00    1188.10
474   INFY     EQ  16-May-2018     1194.55     1187.25     1198.00    1184.50
475   INFY     EQ  17-May-2018     1189.95     1196.00     1197.45    1173.55
476   INFY     EQ  18-May-2018     1182.90     1183.00     1186.55    1173.00
477   INFY     EQ  21-May-2018     1183.20     1179.55     1188.40    1170.00
478   INFY     EQ  22-May-2018     1179.50     1175.00     1198.00    1173.90
479   INFY     EQ  23-May-2018     1193.85     1195.00     1207.65    1181.50
480   INFY     EQ  24-May-2018     1184.90     1198.00     1227.55    1198.00
481   INFY     EQ  25-May-2018     1221.00     1230.10     1248.65    1220.80
482   INFY     EQ  28-May-2018     1228.30     1231.00     1232.60    1206.00
483   INFY     EQ  29-May-2018     1214.40     1214.05     1226.55    1206.20
484   INFY     EQ  30-May-2018     1216.70     1217.00     1228.75    1205.60
485   INFY     EQ  31-May-2018     1211.70     1211.70     1242.00    1210.25
486   INFY     EQ  01-Jun-2018     1231.80     1230.40     1246.25    1217.20
487   INFY     EQ  04-Jun-2018     1220.80     1221.10     1243.00    1212.00
488   INFY     EQ  05-Jun-2018     1239.40     1242.00     1242.00    1217.00
489   INFY     EQ  06-Jun-2018     1220.85     1225.20     1241.55    1220.05
490   INFY     EQ  07-Jun-2018     1237.45     1238.00     1258.00    1238.00
491   INFY     EQ  08-Jun-2018     1252.45     1248.00     1262.00    1246.05
492   INFY     EQ  11-Jun-2018     1260.05     1265.55     1270.00    1255.05
493   INFY     EQ  12-Jun-2018     1262.40     1265.75     1271.25    1250.45
494   INFY     EQ  13-Jun-2018     1258.50     1266.80     1284.00    1266.80
495   INFY     EQ  14-Jun-2018     1274.80     1253.00     1253.00    1234.10
496   INFY     EQ  15-Jun-2018     1239.70     1237.00     1291.50    1235.00

     Last Price  Close Price  Average Price  Total Traded Quantity  \
0       1186.30      1186.00        1179.61                2651282
1       1179.45      1179.50        1179.51                4257541
2       1207.00      1208.75        1199.39                3114783
3       1206.50      1206.10        1204.61                2380862
4       1197.35      1199.50        1199.49                1515629
5       1210.75      1211.60        1203.62                1914313
6       1191.20      1194.55        1187.02                3904174
7       1165.05      1166.20        1170.54                2791889
8       1158.95      1159.15        1161.08                3827987
9       1177.00      1176.85        1169.63                2729575
10      1171.90      1170.80        1173.73                4673112
11      1171.05      1172.40        1174.40                1995956
12      1185.00      1183.95        1186.25                2690661
13      1174.00      1175.45        1176.77                1798208
14      1160.00      1157.25        1159.93                2977438
15      1161.95      1158.20        1161.28                2775824
16      1173.75      1175.05        1169.68                3334441
17      1176.00      1176.55        1174.18                3098684
18      1192.30      1193.80        1186.15                2637710
19      1177.65      1176.25        1179.62                3706664
20      1070.80      1072.55        1085.37               30742063
21      1081.00      1081.95        1072.00                7166412
22      1088.00      1086.95        1082.75                5202322
23      1083.50      1083.10        1081.83                4911448
24      1080.10      1079.90        1079.65                4334001
25      1074.50      1072.45        1070.52                4693269
26      1079.40      1080.85        1075.57                4234776
27      1086.05      1088.70        1085.65                3594805
28      1084.00      1085.35        1085.13                3715910
29      1077.00      1077.50        1078.63                5629281
..          ...          ...            ...                    ...
467     1184.00      1183.00        1181.67                2319480
468     1167.50      1165.55        1167.51                2859278
469     1172.00      1170.70        1169.95                1891752
470     1170.00      1168.00        1173.06                1591431
471     1180.60      1180.75        1174.30                1655853
472     1190.50      1189.30        1184.18                2216047
473     1195.20      1194.55        1196.60                2805987
474     1190.70      1189.95        1191.85                3102502
475     1180.00      1182.90        1186.19                4759799
476     1180.00      1183.20        1181.08                3569830
477     1183.20      1179.50        1182.21                4237660
478     1195.00      1193.85        1189.56                2818402
479     1182.95      1184.90        1198.40                4769221
480     1220.00      1221.00        1217.23                4870285
481     1229.55      1228.30        1239.09                4450719
482     1212.10      1214.40        1218.07                2869897
483     1219.90      1216.70        1214.01                1694467
484     1210.40      1211.70        1214.64                3161533
485     1238.00      1231.80        1230.20                9860170
486     1222.20      1220.80        1229.79                2499178
487     1241.00      1239.40        1233.14                2135078
488     1218.85      1220.85        1226.49                2355431
489     1238.10      1237.45        1234.18                2019092
490     1249.30      1252.45        1252.57                3338113
491     1258.80      1260.05        1257.48                3229939
492     1261.00      1262.40        1262.71                2585645
493     1259.00      1258.50        1258.01                3919910
494     1275.00      1274.80        1275.20                2883464
495     1240.00      1239.70        1242.78                3799424
496     1288.80      1281.25        1267.10                9978880

         Turnover  No. of Trades  Deliverable Qty  % Dly Qt to Traded Qty
0    3.127477e+09          96066          1894154                   71.44
1    5.021828e+09          84979          3232375                   75.92
2    3.735848e+09          84105          2081632                   66.83
3    2.868014e+09          57770          1616360                   67.89
4    1.817989e+09          52549          1015538                   67.00
5    2.304106e+09         102672          1323086                   69.12
6    4.634323e+09          80878          2621701                   67.15
7    3.268027e+09          95815          1918370                   68.71
8    4.444586e+09         140277          2706114                   70.69
9    3.192594e+09          91172          1881552                   68.93
10   5.484982e+09         117143          3365862                   72.03
11   2.344043e+09          83613          1349474                   67.61
12   3.191792e+09          97976          1883547                   70.00
13   2.116084e+09          61330          1243480                   69.15
14   3.453632e+09         131833          2162386                   72.63
15   3.223521e+09         123336          1961216                   70.65
16   3.900243e+09          97975          2357850                   70.71
17   3.638404e+09          90016          2373310                   76.59
18   3.128727e+09          73207          1749653                   66.33
19   4.372440e+09         102739          2124160                   57.31
20   3.336659e+10         707440         16865349                   54.86
21   7.682362e+09         240953          3765678                   52.55
22   5.632802e+09         178219          3912904                   75.21
23   5.313370e+09         104095          3748211                   76.32
24   4.679194e+09         130542          3410877                   78.70
25   5.024245e+09          93296          3540180                   75.43
26   4.554802e+09          97327          3134896                   74.03
27   3.902695e+09          60846          2779791                   77.33
28   4.032230e+09          65130          2545863                   68.51
29   6.071912e+09          84046          4011003                   71.25
..            ...            ...              ...                     ...
467  2.740858e+09          66189          1381557                   59.56
468  3.338246e+09         121067          1833756                   64.13
469  2.213260e+09          50914          1226653                   64.84
470  1.866844e+09          55801           925580                   58.16
471  1.944465e+09          51911          1040917                   62.86
472  2.624192e+09         118716          1385502                   62.52
473  3.357655e+09         169798          1400617                   49.92
474  3.697718e+09          80951          2232738                   71.97
475  5.646034e+09         108694          3495536                   73.44
476  4.216242e+09         118691          2739080                   76.73
477  5.009805e+09          94593          3233546                   76.30
478  3.352664e+09          92075          1959648                   69.53
479  5.715433e+09         155510          3565469                   74.76
480  5.928236e+09         115622          2635888                   54.12
481  5.514861e+09         165203          2833196                   63.66
482  3.495735e+09         114363          1860121                   64.81
483  2.057107e+09          97963          1020909                   60.25
484  3.840109e+09         113600          1820341                   57.58
485  1.212997e+10         163732          6917924                   70.16
486  3.073467e+09          81969          1396541                   55.88
487  2.632848e+09          69180          1356014                   63.51
488  2.888924e+09          85171          1469405                   62.38
489  2.491930e+09          98002          1157667                   57.34
490  4.181210e+09         106204          1876344                   56.21
491  4.061575e+09         146437          2152796                   66.65
492  3.264923e+09          94087          1883057                   72.83
493  4.931300e+09          90357          2684852                   68.49
494  3.676982e+09         110178          1736971                   60.24
495  4.721844e+09         142371          2234217                   58.80
496  1.264429e+10         156513          7198132                   72.13

[497 rows x 15 columns]

In [8]:
print(df['Open Price'].max())

1266.8

In [9]:
print(df['Open Price'].mean())

1029.37635815

In [10]:
df.fillna(0,inplace=True)
print(df['Open Price'].mean())

1029.37635815